### ISSUE TITLE
メールアドレス、パスワード保管

### ISSUE THREAD

**Issue by mokotya** [mobarisu/mobarisu#143]
重複チェック通過後保管テーブルにメールアドレスとパスワードを登録しておく
param

- mail_address(varchar(255))
- password(varchar(255))

return

- (boolean)

**Comment by sakuagl** [comment]
query : INSERT INTO cash (time_cash, mail_address, password) VALUES (DATE_FORMAT(NOW(), '%Y-%m-%d %H:%i:%s'), 'メールアドレス', 'パスワード');
